development:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: loveleeboutique_development
  username: postgres

test:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: loveleeboutique_test
  username: postgres
