development:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: yabies_development
  username: postgres

test:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: yabies_test
  username: postgres
